spring:
  application:
    name: billing-service-test

  data:
    mongodb:
      database: billing_test
      host: localhost
      port: 27017

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: billing-service-test
      auto-offset-reset: earliest
      enable-auto-commit: false

cloud:
  aws:
    region:
      static: us-east-1
    sqs:
      endpoint: http://localhost:4566

aws:
  sqs:
    queues:
      os-events: os-events-queue
      billing-events: billing-events-queue

logging:
  level:
    root: INFO
    br.com.grupo99: DEBUG
    org.springframework.data.mongodb: DEBUG
    io.cucumber: DEBUG

management:
  endpoints:
    enabled-by-default: false
  metrics:
    export:
      newrelic:
        enabled: false
